FROM appplant/go-cli:glibc-2.14
MAINTAINER Sebastian Katzer "haertel@appplant.de"

RUN go get github.com/urfave/cli

RUN mkdir $GOPATH/src/github.com/appplant
RUN mkdir $GOPATH/src/github.com/appplant/alpinepass

ENV ORBIT_HOME $APP_HOME/bintest/orbit
ENV ALPINEPASS_HOME $GOPATH/src/github.com/appplant/alpinepass
