FROM appplant/go-cli:glibc-2.14
MAINTAINER Stefan Härtel "haertel@appplant.de"

RUN go get github.com/urfave/cli
RUN go get github.com/fatih/structs
RUN go get gopkg.in/yaml.v2
RUN go get github.com/stretchr/testify/assert

RUN mkdir $GOPATH/src/github.com/appPlant
RUN mkdir $GOPATH/src/github.com/appPlant/alpinepass

ENV ORBIT_HOME $APP_HOME/bintest/orbit
ENV AP_HOME $GOPATH/src/github.com/appPlant/alpinepass
