#!/bin/sh

docker-compose -f docker-compose.common.yml -f docker-compose.musl.yml build bintest
docker-compose -f docker-compose.common.yml -f docker-compose.musl.yml run bintest

docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml build bintest
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml run bintest
